package org.circadia.generalizedOperations.enums;

public enum ConfigJson {
   APP_PACKAGE, APP_ACTIVITY,  PLATFORM_NAME, ANDROID_VERSION, APPIUM_URL,
   BROWSER_CHROME, WEB_PORTAL_URL, AVD_NAME, DEVICE_NAME, APK_NAME, APK_VERSION
}